---
## Run keycopy for no password login first

- hosts: nohcws
  become: yes
  vars:
    - username: zhiwtong
    - home: home

  tasks:
    - name: 
      authorized_key:
        user: zhiwtong
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        # regexp: '^$USER  ALL='
        line: 'zhiwtong ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Switch to dtas-dev as primary user
      raw: sudo amazon-config-write primary_user dtas-dev

    - name: Switch to dtas-hosts as primary group
      raw: sudo amazon-config-write primary_group dtas-hosts

    - name: Run hosts manage to apply all the changes
      raw: sudo manage --force

    # - name: Reboot the hosts 
    #   raw: sudo reboot

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami


- hosts: nohcws
  become: yes
  vars:
    - username: dtas-dev
    - home: home

  tasks:
    # - name: 
    #   authorized_key:
    #     user: dtas-dev
    #     state: present
    #     key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Install sshpass
      ansible.builtin.apt:
        name: sshpass

    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        # regexp: '^$USER  ALL='
        line: 'dtas-dev ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

- hosts: nohcws
  become: yes
  vars:
    - username: dtas-dev
    - home: home

  tasks:
    - name: Install sshpass
      ansible.builtin.apt:
        name: sshpass

    - name: Validate the sudoers file before saving
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        # regexp: '^$USER  ALL='
        line: 'dtas-dev ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s